# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sindhu10
# "service" is the name of this project. This will also be added to your AWS resource names.
service: email-api

provider:
  name: aws
  runtime: python3.12
  timeout: 30
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

plugins:
  - serverless-offline

functions:
  send_email:
    handler: handler.send_email
    events:
      - http:
          path: dev/send-email
          method: post
